### ISSUE TITLE
error on run 

### ISSUE THREAD

**Issue by itree** [andrewpthorp/simple-http-server#7]
/usr/local/lib/node_modules/simple-http-server/lib/server.js:113
      libs.path.exists(fullPath, function(exists){
                ^
TypeError: undefined is not a function
    at Server.<anonymous> (/usr/local/lib/node_modules/simple-http-server/lib/server.js:113:17)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by timobehrens** [comment]
same here
